### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by MariaHei** [estnltk/word2vec-models#1]
Hi,

I was wondering under which license these embeddings are distributed?

Best,
Maria

**Comment by soras** [comment]
Hi,

The license is CC BY-SA 4.0. 
A bit more information about the models can be found here: https://github.com/estnltk/estnltk/blob/main/tutorials/nlp_pipeline/E_embeddings/word2vec.ipynb

Best,
Siim

**Comment by MariaHei** [comment]
Perfect, thanks so much!
